/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thbar7035
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        item1Input = new javax.swing.JTextField();
        item2Input = new javax.swing.JTextField();
        item3Input = new javax.swing.JTextField();
        item4Input = new javax.swing.JTextField();
        item5Input = new javax.swing.JTextField();
        item1CostLabel = new javax.swing.JLabel();
        item2CostLabel = new javax.swing.JLabel();
        item3CostLabel = new javax.swing.JLabel();
        item4CostLabel = new javax.swing.JLabel();
        item5CostLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        taxLabel = new javax.swing.JLabel();
        taxOutput = new javax.swing.JLabel();
        isolatedCost = new javax.swing.JLabel();
        isolatedOutput = new javax.swing.JLabel();
        combined = new javax.swing.JLabel();
        combinedOutput = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Bell Gothic Std Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Pocket Full of Sand");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(105, 154, 78));

        titleLabel.setFont(new java.awt.Font("Umberto", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 102, 51));
        titleLabel.setText("BUY SOMETHING, STUPID");

        instructionsLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        instructionsLabel.setForeground(new java.awt.Color(51, 102, 0));
        instructionsLabel.setText("Put the number of things you want of the thing in the box, and if you dont want the thing then put a zero");

        item1.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item1.setForeground(new java.awt.Color(51, 255, 51));
        item1.setText("Human Waste");

        item2.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item2.setForeground(new java.awt.Color(51, 255, 51));
        item2.setText("Skin Pants");

        item3.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item3.setForeground(new java.awt.Color(51, 255, 255));
        item3.setText("Pocket Full of Sand");

        item4.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item4.setForeground(new java.awt.Color(51, 255, 51));
        item4.setText("Litterally just an Egg");

        item5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5.setText("Borger");

        item1Input.setBackground(new java.awt.Color(102, 102, 0));

        item2Input.setBackground(new java.awt.Color(0, 153, 0));

        item3Input.setBackground(new java.awt.Color(0, 102, 51));

        item4Input.setBackground(new java.awt.Color(153, 255, 153));

        item5Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5InputActionPerformed(evt);
            }
        });

        item1CostLabel.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item1CostLabel.setForeground(new java.awt.Color(51, 255, 51));
        item1CostLabel.setText("$3.99");

        item2CostLabel.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item2CostLabel.setForeground(new java.awt.Color(51, 255, 51));
        item2CostLabel.setText("$18.99");

        item3CostLabel.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item3CostLabel.setForeground(new java.awt.Color(51, 255, 51));
        item3CostLabel.setText("$9.99");

        item4CostLabel.setFont(new java.awt.Font("AbcBulletin", 0, 14)); // NOI18N
        item4CostLabel.setForeground(new java.awt.Color(51, 255, 51));
        item4CostLabel.setText("$0.65");

        item5CostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        item5CostLabel.setText("1");

        calculateButton.setBackground(new java.awt.Color(255, 255, 51));
        calculateButton.setForeground(new java.awt.Color(255, 255, 204));
        calculateButton.setText("MATH IT");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        taxLabel.setFont(new java.awt.Font("Allegro BT", 1, 14)); // NOI18N
        taxLabel.setForeground(new java.awt.Color(204, 255, 0));
        taxLabel.setText("TAX IS 13% GENIUS");

        taxOutput.setFont(new java.awt.Font("Allegro BT", 0, 14)); // NOI18N
        taxOutput.setForeground(new java.awt.Color(204, 255, 0));
        taxOutput.setText("$0.00");

        isolatedCost.setFont(new java.awt.Font("Allegro BT", 1, 14)); // NOI18N
        isolatedCost.setForeground(new java.awt.Color(204, 255, 0));
        isolatedCost.setText("NOT TAX");

        isolatedOutput.setFont(new java.awt.Font("Allegro BT", 0, 14)); // NOI18N
        isolatedOutput.setForeground(new java.awt.Color(204, 255, 0));
        isolatedOutput.setText("$0.00");

        combined.setFont(new java.awt.Font("Allegro BT", 1, 14)); // NOI18N
        combined.setForeground(new java.awt.Color(204, 255, 0));
        combined.setText("All Together");

        combinedOutput.setFont(new java.awt.Font("Allegro BT", 0, 14)); // NOI18N
        combinedOutput.setForeground(new java.awt.Color(204, 255, 0));
        combinedOutput.setText("$0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(instructionsLabel)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(item3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(item3CostLabel))
                            .addComponent(item4CostLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combined)
                                    .addComponent(isolatedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taxOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combinedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(item2CostLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(item1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(item1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(item1CostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(item4)
                .addGap(10, 10, 10)
                .addComponent(item4Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isolatedCost)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(item5CostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(item5Input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionsLabel)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1)
                    .addComponent(item1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1CostLabel)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item2)
                    .addComponent(item2CostLabel)
                    .addComponent(item2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item3)
                            .addComponent(item3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item3CostLabel))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item4)
                            .addComponent(item4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item4CostLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(item5)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(item5CostLabel)
                                .addGap(16, 16, 16)
                                .addComponent(item5Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(taxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxOutput)
                        .addGap(26, 26, 26)
                        .addComponent(isolatedCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isolatedOutput)
                        .addGap(18, 18, 18)
                        .addComponent(combined)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combinedOutput)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        double itemOne;
        double itemTwo;
        double itemThree;
        double itemFour;
        double itemFive;
        
        double item1Cost = 3.99;
        double item2Cost = 18.99;
        double item3Cost = 9.99;
        double item4Cost = 0.65;
        double item5Cost = 1;
        
        double item1total;
        double item2total;
        double item3total;
        double item4total;
        double item5total;
        
        double subtotal;
        double tax;
        double total;
        
        itemOne = Double.parseDouble(item1Input.getText());
        itemTwo = Double.parseDouble(item2Input.getText());
        itemThree = Double.parseDouble(item3Input.getText());
        itemFour = Double.parseDouble(item4Input.getText());
        itemFive = Double.parseDouble(item5Input.getText());
        
        item1total = itemOne*item1Cost;
        item2total = itemTwo*item2Cost;
        item3total = itemThree*item3Cost;
        item4total = itemFour*item4Cost;
        item5total = itemFive*item5Cost;
        
        
        subtotal = item1total+item2total+item3total+item4total+item5total;
        tax = subtotal*0.13;
        tax = tax * 100;
        tax = Math.round(tax);
        tax = tax / 100;
        total = subtotal*1.13;
        total = total * 100;
        total = Math.round(total);
        total = total / 100;
        
        
        isolatedOutput.setText("$" + subtotal);
        taxOutput.setText("$" + tax);
        combinedOutput.setText("$" + total);
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void item5InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item5InputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel combined;
    private javax.swing.JLabel combinedOutput;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JLabel isolatedCost;
    private javax.swing.JLabel isolatedOutput;
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item1CostLabel;
    private javax.swing.JTextField item1Input;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item2CostLabel;
    private javax.swing.JTextField item2Input;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel item3CostLabel;
    private javax.swing.JTextField item3Input;
    private javax.swing.JLabel item4;
    private javax.swing.JLabel item4CostLabel;
    private javax.swing.JTextField item4Input;
    private javax.swing.JLabel item5;
    private javax.swing.JLabel item5CostLabel;
    private javax.swing.JTextField item5Input;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel taxOutput;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
